sirinsidiator/ESO-LibAddonMenu

LibAddonMenu-2.0/LibAddonMenu-2.0.txt
LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua
info/changelog.txt
info/description.txt
info/info.txt

Fix for #2.
I did a few test with 3 addons that use r14, r16 and r17 and succeeded in adding a lazy initialization that will prevent exceptions in the future.
I also added a helpful warning message that tells users that an older version of lam was loaded and where they should look for help + some help text in the description.
It could need some additional testing and I still need to write a wiki page which outlines what users can do by themselves when the warning is shown.

Load Issues fix

---

LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua

As the title says. If there are two addons calling RegisterAddonPanel prematurely, the first will be reported and set `hasInitialized = true`. The other won't go into Initialize and won't be reported.

always check safeToInitialize, even if initialization was already done

---

LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/button.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/checkbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/colorpicker.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/custom.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/editbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/panel.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/slider.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/texture.lua

#7 rebased onto current `development`. The first two commits are mere cleanup.
The third one is the thing. It replaces the Addon Settings window with a completely new one, separate from OPTIONS_WINDOW (which LAM previously occupied for background and title). Addon panels are now children of the LAM window, with no background of their own. As a consequence, it's not possible to display a LAM-registered panel directly (bypassing OpenToPanel) anymore. If someone uses LAMCC.panel directly, they might need to add their own background.
Be warned that my subscription runs out in 4 days or so, then I'm out for a week at least.

Addon Setttings window revamp

---

LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/button.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/checkbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/colorpicker.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/custom.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/editbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/panel.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/slider.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/texture.lua

The widget consists of 3 elements:
* magnifier button - always shown
* text field - always shown, but not actually visible if empty
* backdrop with a frame - only shown when:
* you hover over the widget, *or*
* the text field has keyboard focus, *or*
* the text field is not empty
The magnifier button, when pressed, clears the text field. If the field had keyboard focus prior to the click, it will take it back.
When the text field is empty (or contains only whitespace), no filtering happens, all add-ons are shown. In this state, the frame around the widget is gray, and the magnifier shows its *normal* icon (or *over* when hovered).
Once you enter some text, add-ons are immediately filtered. The frame around the widget turns blue, and the magnifier switches to *pressed* icon.

Searchbox - filtering add-on list by name, keywords, author

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/button.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/checkbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/colorpicker.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/dropdown.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/editbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/iconpicker.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/slider.lua

Previously, controls initially enabled (controlData.disabled == false)
would not have their disabled status updated on refresh. This problem existed with all controls which were eligible to be disabled.

allow initially enabled controls to be refreshed

---

LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/description.lua

`SetDimensionConstraints` can be passed `0` to set no min/max, that's all this change does.
some examples:
[keeptooltip.lua#24](http://esodata.uesp.net/current/src/ingame/map/keeptooltip.lua.html#24)
[championperks.lua#2222](http://esodata.uesp.net/current/src/ingame/championperks/championperks.lua.html#2222)
-Terrillyn

removed height constraints on description control

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/editbox.lua

changes how editboxes are sized, labels now on top instead of beside editbox; this should make editing longer texts easier. Text should also be aligned better.
-Terrillyn

improved editbox sizing

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/slider.lua

fix for issue #21 
Allows use of `decimals` property on sliders to limit the number of decimals

fix for issue #21, added 'decimals' property

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/slider.lua

adds mousewheel support to slide controls (#30)
_doesn't work when step has too many decimal places e.g. `0.00001`._

feature request #30

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/slider.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/texture.lua

Hey @sirinsidiator, I noticed that a couple widgets in LAM-2.0 had wired up the wrong mouse exit events for clearing tooltips.  Here's a fix.

Fix tooltip mouse exit events for sliders and textures

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/divider.lua

I wanted a way to divide up minor groupings of content under the same title without resorting to a sub-menu or introducing new headers.  
I basically ended up just making a header without any text, reduced the opacity and called it a "divider".
http://screencast.com/t/z8vJzTfP9pS
Might not be worth including, but I figured I'd provide the code anyways, just in case.

New widget "divider" 

---

LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/button.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/checkbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/colorpicker.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/dropdown.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/editbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/iconpicker.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/panel.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/slider.lua

I needed the ability to have the warning icon refresh its tooltip or completely hide (if warning was set to a function that returns nil) during a panel refresh for one of my addons.  So I went ahead and implemented the feature for all widgets that have a warning setting.  Code provided here in case you think it's worth including in the next release.  No offense if you don't want it, though.

Update warning tooltips during panel refresh.

---

LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua

Bugfix for controls not properly refreshed if control was in a submenu, which was in a submenu, ...
-> Parent panel was the submenu and not the top parent panel. So the variable registerForRefresh was missing

Relating to issue #61

---

LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua

Use GetStringFromValue in debug code to avoid errors when the name property is of the function type. Spent quite a bit of time debugging for someone until I discovered this was causing additional problems.

Debug code and function-type name property

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/submenu.lua

This change does:
- add the "disabled" entry to reference a function for disabling the submenu (like other widgets)
- in case "disabled" is true, change the submenu label colour to a greyed out version (and reverse)
This change does NOT:
- disable any child-widgets that belong to the submenu
- prevent the submenu from collapsing/expanding
- close the expanded submenu when it is disabled

add [disabled] to submenu

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/description.lua

Similar to the new "disabledLabel" for the submenu, the "disabledDesc" can change the font-color of a description and disable it.
Default (either w/o disabledLabel, or disabledLabel is returning false)
Disabled (disabledLabel returning true)

add "disabledDesc" for disabling (i.e. greying out) the description text

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/description.lua

Three possible values allowed:
- `nil` (default): links are disabled
- `true`: links clicks will call `ZO_LinkHandler_OnLinkClicked(linktext, button)`
- `function(labelControl, linkData, linkText, button, ctrl, alt, shift, command) end`: the custom function passed will be called upon link click.

New "enableLinks" option for description widget

---

LibAddonMenu-2.0/LibAddonMenu-2.0/controls/slider.lua

with "off" you can disable the input and use it only for viewing

added readOnly for sliders

---

LibAddonMenu-2.0/LibAddonMenu-2.0/LibAddonMenu-2.0.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/button.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/checkbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/colorpicker.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/description.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/dropdown.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/editbox.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/header.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/iconpicker.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/slider.lua
LibAddonMenu-2.0/LibAddonMenu-2.0/controls/submenu.lua

[Widget versions were not yet increased! Please do  so if neccessary]
-Added attribute helpUrl to most widgets
-Added functions to LibAddonMenu-2.0.lua to create a FAQ texture (?) control at the widget controls (next right of their label text's width, or if no label is given right of the widget control)
-Hovering the texture will show "Open website: " .. url
-Clicking the texture will open the URL open dialog of ESO

Added FAQ / helpURL at widgets

---

.gitignore
LibAddonMenu-2.0/LibAddonMenu-2.0.lua
LibAddonMenu-2.0/controls/custom.lua
LibAddonMenu-2.0/controls/description.lua
LibAddonMenu-2.0/controls/texture.lua

fixes blank log lines like this.
```
2023-12-29T14:49:44.685-06:00 |cff0000Gui Warning:  has a set width but has resizeToFitDescendents enabled. If this is intended, use resizeToFitConstrains="Y".|r
2023-12-29T14:49:45.128-06:00 |cff0000Gui Warning:  has a set width but has resizeToFitDescendents enabled. If this is intended, use resizeToFitConstrains="Y".|r
2023-12-29T14:49:45.996-06:00 |cff0000Gui Warning:  has a set width but has resizeToFitDescendents enabled. If this is intended, use resizeToFitConstrains="Y".|r
2023-12-29T14:49:45.996-06:00 |cff0000Gui Warning:  has a set width but has resizeToFitDescendents enabled. If this is intended, use resizeToFitConstrains="Y".|r
2023-12-29T14:49:45.996-06:00 |cff0000Gui Warning:  has a set width but has resizeToFitDescendents enabled. If …
```

anchor constrains fix

---

LibAddonMenu-2.0/controls/dropdown.lua

https://github.com/Baertram/ESO-LibAddonMenu/blob/master/LibAddonMenu-2.0/controls/dropdown.lua#L73-L97 currently only clears dropdown.m_selectedItemData, but m_enableMultiSelect dropdowns use m_multiSelectItemData instead. Because that isn't cleared, dropdown:SetSelectedItemByEval resolves eventually into SelectItem (which, in /EsoUI/Libraries/ZO_ComboBox/ZO_ComboBox.lua:341, self:RemoveItemFromSelected(item) if the item was already self:IsItemSelected(item) ). So ultimately, UpdateMultiSelectSelected currently untoggles everything when called (for multiSelect only).
This fixes that by clearing m_multiSelectItemData also.
For clarification, the repro steps:
1. Have any multi-select dropdowns with elements selected in them
2. Do anything to any other control in the same panel while …

Fix multi-select dropdowns flip-flopping between empty and not
